### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ghost** [wemeetagain/eth-id#1]
Please license this code so we can be certain about its reusability.

> As Brian Doll, GitHub's VP of Marketing [explains it here](http://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html):
> 
> Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.

**Comment by wemeetagain** [comment]
Now licensed, thanks.
